name: Create Release
on: 
  push:
    branches: master
    tags:
      - v*

permissions:
  contents: write

jobs:
  release_build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create local gradle properties files
        run: touch local.properties

      - name: Add Google Maps API Key
        run: echo "MAPS_API_KEY=${{secrets.MAPS_API_KEY}}" >> local.properties

      # Here we need to decode keystore.jks from base64 string and place it
      # in the folder specified in the release signing configuration
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2.3
        with:
          fileName: 'android_keystore.jks'
          fileDir: '/home/runner/work/<<project name>>/<<project name>>/app/keystore/'
          encodedString: ${{ secrets.SIGNING_KEYSTORE }}

      - name: Build Release APK
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew build -x lint -x lintVitalRelease

      - name: Build Release Bundle
        run: ./gradlew bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload Build to artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: release-artifacts
          path: |
            app/build/outputs/debug/app-debug.apk
            app/build/outputs/bundle/release/
      
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/bundle/release/app-release.aab
