name: Testing APK
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Clean Gradle
        run: ./gradlew clean
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      
